//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Ressource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Ressource.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to action has been canceled.
        /// </summary>
        public static string ApplicationActionCancelled {
            get {
                return ResourceManager.GetString("ApplicationActionCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action as failed.
        /// </summary>
        public static string ApplicationActionFailed {
            get {
                return ResourceManager.GetString("ApplicationActionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the field &apos;{0}&apos; is required in the action parameter.
        /// </summary>
        public static string ApplicationActionFieldRequired {
            get {
                return ResourceManager.GetString("ApplicationActionFieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to action with guid {0} non existant.
        /// </summary>
        public static string ApplicationActionNotFound {
            get {
                return ResourceManager.GetString("ApplicationActionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application run successfully.
        /// </summary>
        public static string ApplicationActionRunSuccess {
            get {
                return ResourceManager.GetString("ApplicationActionRunSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error during event handler &apos;{0}&apos;, message : {1}.
        /// </summary>
        public static string ErrorDuringEventHandler {
            get {
                return ResourceManager.GetString("ErrorDuringEventHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error with package {0}, message : &apos;{1}&apos;.
        /// </summary>
        public static string ErrorWithPlatypusApplicationPackage {
            get {
                return ResourceManager.GetString("ErrorWithPlatypusApplicationPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new action has been started.
        /// </summary>
        public static string NewApplicationActionStarted {
            get {
                return ResourceManager.GetString("NewApplicationActionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there is no action with guid &apos;{0}&apos;.
        /// </summary>
        public static string NoApplicationActionWithGuid {
            get {
                return ResourceManager.GetString("NoApplicationActionWithGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there is no application with guid &apos;{0}&apos;.
        /// </summary>
        public static string NoApplicationWithGuid {
            get {
                return ResourceManager.GetString("NoApplicationWithGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there is no user connection method with the guid &apos;{0}&apos;.
        /// </summary>
        public static string NoUserConnectionMethodWithGuid {
            get {
                return ResourceManager.GetString("NoUserConnectionMethodWithGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the field &apos;{0}&apos; is required.
        /// </summary>
        public static string ParameterEditorFieldRequired {
            get {
                return ResourceManager.GetString("ParameterEditorFieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parameter are required for the action &apos;{0}&apos;.
        /// </summary>
        public static string ParameterRequieredForApplicationAction {
            get {
                return ResourceManager.GetString("ParameterRequieredForApplicationAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default user for platypus application.
        /// </summary>
        public static string PlatypusUserConnectionMethodDescription {
            get {
                return ResourceManager.GetString("PlatypusUserConnectionMethodDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platypus User.
        /// </summary>
        public static string PlatypusUserConnectionMethodName {
            get {
                return ResourceManager.GetString("PlatypusUserConnectionMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation denied to user.
        /// </summary>
        public static string UserNotPermitted {
            get {
                return ResourceManager.GetString("UserNotPermitted", resourceCulture);
            }
        }
    }
}
