//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Ressource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Ressource.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to action has been canceled.
        /// </summary>
        internal static string ApplicationActionCancelledException {
            get {
                return ResourceManager.GetString("ApplicationActionCancelledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action as failed.
        /// </summary>
        internal static string ApplicationActionFailed {
            get {
                return ResourceManager.GetString("ApplicationActionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the field &apos;{0}&apos; is required in the action parameter.
        /// </summary>
        internal static string ApplicationActionFieldRequiredException {
            get {
                return ResourceManager.GetString("ApplicationActionFieldRequiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to action with guid {0} non existant.
        /// </summary>
        internal static string ApplicationActionNotFound {
            get {
                return ResourceManager.GetString("ApplicationActionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application run successfully.
        /// </summary>
        internal static string ApplicationActionRunSuccess {
            get {
                return ResourceManager.GetString("ApplicationActionRunSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new action has been started.
        /// </summary>
        internal static string NewApplicationActionStarted {
            get {
                return ResourceManager.GetString("NewApplicationActionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there is no action with guid &apos;{0}&apos;.
        /// </summary>
        internal static string NoApplicationActionWithGuidException {
            get {
                return ResourceManager.GetString("NoApplicationActionWithGuidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parameter are required for the action &apos;{0}&apos;.
        /// </summary>
        internal static string ParameterRequieredForApplicationActionException {
            get {
                return ResourceManager.GetString("ParameterRequieredForApplicationActionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default user for platypus application.
        /// </summary>
        internal static string PlatypusUserConnectionMethodDescription {
            get {
                return ResourceManager.GetString("PlatypusUserConnectionMethodDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platypus User.
        /// </summary>
        internal static string PlatypusUserConnectionMethodName {
            get {
                return ResourceManager.GetString("PlatypusUserConnectionMethodName", resourceCulture);
            }
        }
    }
}
